-- MySQL Script generated by MySQL Workbench
-- Δευ 15 Αύγ 2016 04:33:50 πμ EEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`User` ;

CREATE TABLE IF NOT EXISTS `mydb`.`User` (
  `UserId` VARCHAR(45) NOT NULL,
  `Trn` VARCHAR(25) NULL DEFAULT NULL,
  `Email` VARCHAR(45) NULL DEFAULT NULL,
  `Phone` VARCHAR(45) NULL DEFAULT NULL,
  `Address` VARCHAR(90) NULL DEFAULT NULL,
  `Country` VARCHAR(45) NULL DEFAULT NULL,
  `Latitude` FLOAT NULL DEFAULT NULL,
  `Longitude` FLOAT NULL DEFAULT NULL,
  `Sell_rating` FLOAT NULL DEFAULT NULL,
  `Bid_rating` FLOAT NULL DEFAULT NULL,
  `Password` VARCHAR(80) NULL DEFAULT NULL,
  `Access_lvl` INT NULL DEFAULT NULL,
  PRIMARY KEY (`UserId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Auction`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Auction` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Auction` (
  `AuctionId` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NULL DEFAULT NULL,
  `Current_Bid` FLOAT NULL DEFAULT NULL,
  `Starting_Bid` FLOAT NULL DEFAULT NULL,
  `Buy_Price` FLOAT NULL DEFAULT NULL,
  `Num_of_bids` INT NULL DEFAULT NULL,
  `Latitude` FLOAT NULL DEFAULT NULL,
  `Longitude` FLOAT NULL DEFAULT NULL,
  `Location` VARCHAR(255) NULL DEFAULT NULL,
  `Country` VARCHAR(45) NULL DEFAULT NULL,
  `Start_time` DATETIME NULL DEFAULT NULL,
  `Expiration_time` DATETIME NULL DEFAULT NULL,
  `Description` LONGTEXT NULL DEFAULT NULL,
  PRIMARY KEY (`AuctionId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`User_bid_Auction`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`User_bid_Auction` ;

CREATE TABLE IF NOT EXISTS `mydb`.`User_bid_Auction` (
  `User_UserId` VARCHAR(45) NOT NULL,
  `Auction_AuctionId` INT NOT NULL,
  `Time` DATETIME NULL DEFAULT NULL,
  `Price` FLOAT NULL DEFAULT NULL,
  PRIMARY KEY (`User_UserId`, `Auction_AuctionId`),
  INDEX `fk_User_has_Auction_Auction1_idx` (`Auction_AuctionId` ASC),
  INDEX `fk_User_has_Auction_User1_idx` (`User_UserId` ASC),
  CONSTRAINT `fk_User_has_Auction_User1`
    FOREIGN KEY (`User_UserId`)
    REFERENCES `mydb`.`User` (`UserId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_User_has_Auction_Auction1`
    FOREIGN KEY (`Auction_AuctionId`)
    REFERENCES `mydb`.`Auction` (`AuctionId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`User_has_Auction`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`User_has_Auction` ;

CREATE TABLE IF NOT EXISTS `mydb`.`User_has_Auction` (
  `User_UserId` VARCHAR(45) NOT NULL,
  `Auction_AuctionId` INT NOT NULL,
  PRIMARY KEY (`User_UserId`, `Auction_AuctionId`),
  INDEX `fk_User_has_Auction_Auction2_idx` (`Auction_AuctionId` ASC),
  INDEX `fk_User_has_Auction_User2_idx` (`User_UserId` ASC),
  CONSTRAINT `fk_User_has_Auction_User2`
    FOREIGN KEY (`User_UserId`)
    REFERENCES `mydb`.`User` (`UserId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_User_has_Auction_Auction2`
    FOREIGN KEY (`Auction_AuctionId`)
    REFERENCES `mydb`.`Auction` (`AuctionId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Message`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Message` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Message` (
  `idMessages` INT NOT NULL AUTO_INCREMENT,
  `User_from` VARCHAR(45) NOT NULL,
  `User_to` VARCHAR(45) NOT NULL,
  `Is_read` TINYINT(1) NOT NULL,
  `Time` DATETIME NOT NULL,
  `Subject` TINYTEXT NOT NULL,
  `Text` LONGTEXT NOT NULL,
  PRIMARY KEY (`idMessages`),
  INDEX `fk_Messages_Users_idx` (`User_from` ASC),
  INDEX `fk_Messages_Users1_idx` (`User_to` ASC),
  CONSTRAINT `fk_Messages_Users`
    FOREIGN KEY (`User_from`)
    REFERENCES `mydb`.`User` (`UserId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Messages_Users1`
    FOREIGN KEY (`User_to`)
    REFERENCES `mydb`.`User` (`UserId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Category` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Category` (
  `Name` VARCHAR(45) NOT NULL,
  `Parent` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`Name`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Image`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Image` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Image` (
  `url` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`url`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Auction_has_Image`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Auction_has_Image` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Auction_has_Image` (
  `Auction_AuctionId` INT NOT NULL,
  `table1_url` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`Auction_AuctionId`, `table1_url`),
  INDEX `fk_Auction_has_table1_table11_idx` (`table1_url` ASC),
  INDEX `fk_Auction_has_table1_Auction1_idx` (`Auction_AuctionId` ASC),
  CONSTRAINT `fk_Auction_has_table1_Auction1`
    FOREIGN KEY (`Auction_AuctionId`)
    REFERENCES `mydb`.`Auction` (`AuctionId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Auction_has_table1_table11`
    FOREIGN KEY (`table1_url`)
    REFERENCES `mydb`.`Image` (`url`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Auction_has_Category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Auction_has_Category` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Auction_has_Category` (
  `Auction_AuctionId` INT NOT NULL,
  `Category_Name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Auction_AuctionId`, `Category_Name`),
  INDEX `fk_Auction_has_Category_Category1_idx` (`Category_Name` ASC),
  INDEX `fk_Auction_has_Category_Auction1_idx` (`Auction_AuctionId` ASC),
  CONSTRAINT `fk_Auction_has_Category_Auction1`
    FOREIGN KEY (`Auction_AuctionId`)
    REFERENCES `mydb`.`Auction` (`AuctionId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Auction_has_Category_Category1`
    FOREIGN KEY (`Category_Name`)
    REFERENCES `mydb`.`Category` (`Name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
